### ISSUE TITLE
ASP Core 3.1 Update

### ISSUE THREAD

**Issue by papyr** [baseeam/baseeam-web-app#20]
Hello @nguyencongle very nice effort.

Any updates to ASP Core 3.1
Also any plans to make it Multi tenant - check out identity server 4 admin - free https://github.com/skoruba/IdentityServer4.Admin

Is there a way to get in touch with you, for any part time development.

thanks

**Comment by nguyencongle** [comment]
You can send email to me: nguyenle@baseeam.com for any discussion.
