### ISSUE TITLE
Migration to [Ms Sql/Express], how to move session state in web config

### ISSUE THREAD

**Issue by weedkiller** [baseeam/baseeam-web-app#21]
Hi, you have 

 ```
  <providers>
        <add name="MySqlSessionStateStore" type="MySql.Web.SessionState.MySqlSessionStateStore
```
    
 in the web config.. how to migrate this to Ms Sql Express or Developer version

https://devblogs.microsoft.com/aspnet/introducing-the-asp-net-async-sessionstate-module/ 

    public abstract class SessionStateStoreProviderAsyncBase : ProviderBase
    {
    public abstract SessionStateStoreData CreateNewStoreData(HttpContextBase context, int timeout);

    public abstract Task CreateUninitializedItemAsync(
        HttpContextBase context,
        string id,
        int timeout,
        CancellationToken cancellationToken);

    public abstract void Dispose();

    public abstract Task EndRequestAsync(HttpContextBase context);

    public abstract Task<GetItemResult> GetItemAsync(
        HttpContextBase context,
        string id,
        CancellationToken cancellationToken);

    public abstract Task<GetItemResult> GetItemExclusiveAsync(
        HttpContextBase context,
        string id,
        CancellationToken cancellationToken);

    public abstract void InitializeRequest(HttpContextBase context);

    public abstract Task ReleaseItemExclusiveAsync(
        HttpContextBase context,
        string id,
        object lockId,
        CancellationToken cancellationToken);

    public abstract Task RemoveItemAsync(
        HttpContextBase context,
        string id,
        object lockId,
        SessionStateStoreData item,
        CancellationToken cancellationToken);

    public abstract Task ResetItemTimeoutAsync(HttpContextBase context, string id, CancellationToken cancellationToken);

    public abstract Task SetAndReleaseItemExclusiveAsync(
        HttpContextBase context,
        string id,
        SessionStateStoreData item,
        object lockId,
        bool newItem,
        CancellationToken cancellationToken);

      public abstract bool SetItemExpireCallback(SessionStateItemExpireCallback expireCallback);
     }

**Comment by nguyencongle** [comment]
You can follow this guide:
https://support.microsoft.com/en-us/help/317604/how-to-configure-sql-server-to-store-asp-net-session-state

**Comment by weedkiller** [comment]
@nguyencongle thanks for the link 👍 but it maybe for ASPX, for use with ASP MVC or Core, the current configuration requires us to add a `<providers>` node
________


```
<sessionState cookieless="false" regenerateExpiredSessionId="true" mode="Custom" customProvider="SqlSessionStateProviderAsync">
    <providers>
        <add name="SqlSessionStateProviderAsync" 
             connectionStringName="MySessionStateConnectionString"
             type="Microsoft.AspNet.SessionState.SqlSessionStateProviderAsync, Microsoft.AspNet.SessionState.SqlSessionStateProviderAsync, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
             UseInMemoryTable="true"
             MaxRetryNumber="5"
             RetryInterval="100" />
    </providers>
</sessionState>
```
_______

Is it possible to turn off Session store from Web Config, I get errors when I turn it off.
Also, any chance we can get a Sql Express version?

**Comment by nguyencongle** [comment]
No, You can't turn off the Session.
The implementation of BaseEAM already has the code for SQL Server (any version).
But we just only had resources to test with MySQL.
But I think it's just the same.

**Comment by weedkiller** [comment]
ok thanks
